apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scdf.fullname" . }}-skipper
  labels:
    app: {{ include "scdf.fullname" . }}-skipper
    {{- include "scdf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "scdf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scdf.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "scdf.serviceAccountName" . }}
      {{- with .Values.skipper.podSecurityContext }}
      securityContext:
        {{- . | nindent 8 }}
      {{- else }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "scdf.fullname" . }}-skipper
          securityContext:
            {{- toYaml .Values.skipper.securityContext | nindent 12 }}
          image: "{{ .Values.skipper.image.repository | default "springcloud/spring-cloud-skipper" }}:{{ .Values.skipper.image.tag | default .Chart.AppVersion }}"
          {{- $GlobalImagePullPolicy := .Values.global.imagePullPolicy | default "IfNotPresent" }}
          imagePullPolicy: {{ .Values.skipper.image.pullPolicy | default $GlobalImagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.skipper.containerPort | default 7577 }}
              protocol: {{ .Values.skipper.protocol | default "TCP" }}
          {{- with mergeOverwrite .Values.global.startupProbe .Values.skipper.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with mergeOverwrite .Values.global.livenessProbe .Values.skipper.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with mergeOverwrite .Values.global.readinessProbe .Values.skipper.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with mergeOverwrite .Values.global.resources .Values.skipper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.skipper.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- else }}
          volumeMounts:
          - name: config
            mountPath: /workspace/config
            readOnly: true
          {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      {{- with .Values.skipper.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ end }}
      {{- with .Values.skipper.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      volumes:
      - name: config
        configMap:
          name: scdf-server
          items:
          - key: 'application-kubernetes.yaml'
            path: 'application-kubernetes.yaml'
      {{- end }}
      {{- with .Values.skipper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
