name: build-uaa-test

on:
  workflow_dispatch:

jobs:
  # test templating before publishing a package
  prepare:
    name: Prepare Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: cloudfoundry/uaa
          ref: '4.32.0'
          path: src/docker/uaa/uaa
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'liberica'
      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build UAA Test Image
        shell: bash
        run: ./src/docker/uaa/build-all
      - name: Publish Test Image
        shell: bash
        run: docker push spring-cloud/scdf-uaa-test:4.32
