name: build-images

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: false
      delete-tags:
        type: boolean
        default: false
        description: 'Delete the image tags'

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  # test templating before publishing a package
  prepare:
    name: Prepare Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Load matrix
        id: matrix
        shell: bash
        run: |          
          if [ "${{ inputs.version }}" == "" ]; then
            ./mvnw help:evaluate -Dexpression=project.version -s .settings.xml -B --no-transfer-progress > /dev/null
            VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "::notice::VERSION=$VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "::notice::VERSION=${{ inputs.version }}"
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          fi          
          MATRIX=$(cat .github/workflows/images.json | jq -c)
          echo "MATRIX=$MATRIX"
          echo "MATRIX=$MATRIX" >> $GITHUB_ENV
    outputs:
      matrix: ${{ env.MATRIX }}
      version: ${{ env.VERSION }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    concurrency:
      group: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Install pack
        uses: jvalkeal/build-zoo-handler@v0.0.4
        with:
          pack-version: 0.30.0
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and Publish ${{ matrix.name }}
        shell: bash
        env:
          TAG: ${{ needs.prepare.outputs.version }}
          DEFAULT_JDK: '17'
          DELETE_TAGS: ${{ inputs.delete-tags }}
        run: |
          .github/workflows/build-image.sh ${{ matrix.path }} ${{ matrix.image }} ${{ matrix.name }}
  build-extra:
    name: Build extra images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Grafana Prometheus
        uses: docker/build-push-action@v2
        with:
          context: src/grafana/prometheus/docker/grafana
          push: true
          tags: springcloud/spring-cloud-dataflow-grafana-prometheus:${{ inputs.version }}
      - name: Publish Grafana InfluxDB
        uses: docker/build-push-action@v2
        with:
          context: src/grafana/influxdb/docker/grafana
          push: true
          tags: springcloud/spring-cloud-dataflow-grafana-influxdb:${{ inputs.version }}
      - name: Publish Prometheus Local
        uses: docker/build-push-action@v2
        with:
          context: src/grafana/prometheus/docker/prometheus-local
          push: true
          tags: springcloud/spring-cloud-dataflow-prometheus-local:${{ inputs.version }}
